
import distutils.sysconfig
env = Environment()
env.ParseConfig("pkg-config --cflags --libs opencv")
print env['CPPPATH']
env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=True

env.Command(
    "interface_wrap.c",
    "interface.i",
    "swig -python -o $TARGET $SOURCE",
)

env.SharedLibrary(
    target = "_libvision",
    SHLIBPREFIX = "",
    source = ["interface_wrap.c", "../libvision.so"],
    CPPPATH = [
        "../include/",
        distutils.sysconfig.get_python_inc(),
    ] + env["CPPPATH"]
)
