#!/bin/sh

CC="/usr/bin/gcc"
CFLAGS="--std=c99 -Wall -pedantic"
INCLUDES="-I../libseawolf/include"
LIBFLAGS="-g -lncurses -lrt -lseawolf -lpthread -L../libseawolf/"
OUTPUTDIR="bin"

. ../misc/make.sh

case "$1" in
  "clean")
    rmNoFail ${OUTPUTDIR}/*
    ;;
  *)
    if [ ! -d ${OUTPUTDIR} ]; then
        runcmd mkdir -p ${OUTPUTDIR};
    fi
    for in in src/*.c; do
        out="${OUTPUTDIR}/`basename ${in} .c`"
        if isOutDated $out $in; then
            runcmd ${CC} ${CFLAGS} ${INCLUDES} -o $out $in ${LIBFLAGS}
        fi
    done;
esac
