
export CC= bfin-linux-uclibc-gcc
export CFLAGS= --std=c99 -Wall -Werror -pedantic -Wmissing-prototypes -I$(PWD)/include -fPIC
export LIB_PATH=$(PWD)
export LIB_NAME=$(LIB_PATH)/libseawolf-bfin.so
export HUB_NAME=$(PWD)/hub

all:
	$(MAKE) -C src $(LIB_NAME)

clean:
	$(MAKE) -C src clean
	rm -rf doc

%:
	$(MAKE) -C src $(PWD)/$@

.PHONY: all clean doc
