#!/bin/sh

CC="/usr/bin/gcc"
CFLAGS="--std=c99 -Wall -pedantic -Iinclude -L. -g"
CFLAGS="${CFLAGS} -DSEAWOLF_DEBUG"
LIBFLAGS="-lmysqlclient_r -lpthread --shared -fPIC"

SRCS=src/*.c
HEADERS=include/seawolf/*.h

. ../misc/make.sh

case "$1" in
  "clean")
    rmNoFail *.so
    rmNoFail hub
    ;;
  "run")
    runcmd export LD_LIBRARY_PATH=../libseawolf/
    runcmd ./serialapp
    ;;
  *)
    if isOutDated libseawolf.so ${SRCS}; then
        runcmd ${CC} ${CFLAGS} ${LIBFLAGS} -o libseawolf.so ${SRCS}
    fi
    if isOutDated hub src/hub/hub.c; then
        runcmd ${CC} ${CFLAGS} -g -o hub src/hub/hub.c
    fi
esac
