#!/bin/sh

. ../misc/make.sh

case "$1" in
  "clean")
    rmNoFail work/* 
    rmNoFail seawolf.pdf
    ;;
  *)
    runcmd latex -output-format=pdf -output-directory=work/ src/seawolf.tex
    runcmd mv work/seawolf.pdf .
esac
