
env = Environment()
env.ParseConfig("pkg-config --cflags --libs opencv")
env.Append(
    CFLAGS=[
        "--std=c99",
        "-DCV_NO_BACKWARD_COMPATIBILITY",
        "-g",
        "-pedantic",
        "-Wmissing-prototypes",
        "-Wall",
        "-Werror",
        "-Wno-unused",
    ],
    CPPPATH=["include/"],
)

env.SharedLibrary(
    target = "vision",
    source = Glob("src/*.c"),
)
