#!/bin/bash
CC="/opt/uClinux/bfin-uclinux/bin/bfin-uclinux-gcc"
CFLAGS="--std=gnu99 -Wall"
LD_FLAGS="-lm -lbfdsp -Wl,-elf2flt"
$CC $CFLAGS -o csv_fft csv_io.c acoustics_math.c csv_fft.c $LD_FLAGS
#$CC $CFLAGS -o csv_ifft csv_io.c acoustics_math.c csv_ifft.c $LD_FLAGS
#$CC $CFLAGS -o csv_flip csv_io.c acoustics_math.c csv_flip.c $LD_FLAGS
#$CC $CFLAGS -o csv_mult csv_io.c acoustics_math.c csv_mult.c $LD_FLAGS
#$CC $CFLAGS -o csv_correlate csv_io.c acoustics_math.c csv_correlate.c $LD_FLAGS
#$CC $CFLAGS -o circbuffer CircularBuffer.c $LDFLAGS
#$CC $CFLAGS -o csv_fast_correlate csv_io.c acoustics_math.c csv_fast_correlate.c $LD_FLAGS
$CC $CFLAGS -o circ_buffer_main acoustics_math.c csv_io.c circ_buffer_main.c $LD_FLAGS
