PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE config (option VARCHAR PRIMARY KEY, value VARCHAR);
INSERT INTO "config" VALUES('password','');
INSERT INTO "config" VALUES('log_file','seawolf.log');

CREATE TABLE variables (id INT AUTO_INCREMENT UNIQUE PRIMARY KEY, time TIMESTAMP, precisetime DOUBLE, name CHAR(20), value FLOAT);

CREATE TABLE variable_definitions (name CHAR(64) UNIQUE PRIMARY KEY, default_value DOUBLE, persistent BOOL, readonly BOOL);
INSERT INTO "variable_definitions" VALUES('LogLevel',2,0,1);
INSERT INTO "variable_definitions" VALUES('LogReplicateStdout',2,0,0);

INSERT INTO "variable_definitions" VALUES('SEA.Roll',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SEA.Yaw',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SEA.Pitch',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IEA.Roll',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IEA.Yaw',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IEA.Pitch',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.MagField.X',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.MagField.Y',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.MagField.Z',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.Accel.X',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.Accel.Y',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.Accel.Z',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.AngRate.X',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.AngRate.Y',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IV.AngRate.Z',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.11',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.21',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.31',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.12',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.22',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.32',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.13',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.23',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('IOM.33',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('Depth',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('DepthHeading',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('Altitude',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('AltitudeHeading',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('YawHeading',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPoint.Theta',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPoint.Phi',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPoint.Rho',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointSource',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointVision.Theta',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointVision.Phi',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointVision.Rho',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointAcoustics.Theta',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointAcoustics.Phi',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointAcoustics.Rho',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointOverride.Theta',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointOverride.Phi',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('SetPointOverride.Rho',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('DepthPID.p',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('DepthPID.i',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('DepthPID.d',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('AltitudePID.p',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('AltitudePID.i',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('AltitudePID.d',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('RollPID.p',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('RollPID.i',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('RollPID.d',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('PitchPID.p',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('PitchPID.i',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('PitchPID.d',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('YawPID.p',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('YawPID.i',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('YawPID.d',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('Aft',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('PortX',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('PortY',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('StarX',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('StarY',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('VisionTarget',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('VisionFound',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('MissionStatus',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('CountDownStatus',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('TrackerDoDepth',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('PIDDoYaw',0.0,1,0);
INSERT INTO "variable_definitions" VALUES('PingDelay.a',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('PingDelay.b',0.0,0,0);
INSERT INTO "variable_definitions" VALUES('PingDelay.c',0.0,0,0);
COMMIT;
